### ISSUE TITLE
Desdobramentos Reunião Luísa

### ISSUE THREAD

**Issue by YanVieira1905** [automatiza-mg/handbook#76]
## Encaminhamentos pós reunião secretária - Automatiza-mg
- [x] automatiza-mg/automatizacoes#71
    - atualmente, temos palavras-chave, mas que podem duplicar os robôs criados na página da biblioteca
    - também temos mecanismo de busca por palavra-chave
    - os dois mecanismos acima têm limitações; por exemplo, não há hierarquia de tags, e também não há categorização dos resultados da busca (mistura post, robô do catálogo, frases de dentro dos textos, títulos dos textos, etc)
    - índice do lado esquerdo ajuda a navegar pelos documentos, índice do lado direito ajuda a navegar dentro do documento da página aberta em primeiro plano
    - Distinguir entre robôs blocos/legos e robôs reproduzíveis (que pode ser utilizado por mais de um órgão).
Reproduzíveis podem utilizar a estrutura dos robôs de bloco.
- [x] definir níveis de hierarquia (quais e quantos) para fragmentos de robô
    - SEI (ofício, memorando, parecer, blocos)
    - SIAFI (empenhar, liquidar, pagar, etc)
    - SISAD
    - etc 
- [x] formato curso EAD
    - tem teste? diploma poderia ter requisito 
    - possibilidade de aproveitar materiais preparados (escrever conteúdo antes da gravação)
    - ver contatos no TCE para verificar requisitos de elaboração/gravação do curso (Ana < - @YanVieira1905 )
    - carga horária (qual parâmetro): trade-off entre complexidade do robô (carga horária mais alta_ X incentivo a fazer o curso; certificado de particpação por assistir as aulas (4h)/ nº mínimo de ações (12h)/robô inédito (80h?) que resolva um problema prático do setor
- [x] data-limite evento lançamento projeto: final de março, necessitando de:
  - site Automatiza
  - resultados fechamento SCAP
  - formato curso EAD parceria TCE
  - etc
  - reunião Secretária e governador: prevista para 17/03 
- [ ] Rede de simplificação será responsável por multiplicar ações do projeto automatização.
  - Comunicação com Secretário.
  - Possibilidade de curso automate presencial para este ator.
  - Identificar perfil dessas pessoas.
  - A ideia seria refazer esta rede, então partir do zero. @YanVieira1905 ficará responsável por isso e ação será tomada após reunião com Governador.
- [x] Novos computadores serão disponibilizados para o projeto e alinhamento já foi feito com área responsável.
- [x] Instalação do Automate sem precisar abrir chamado x admin para equipe responsável.
- [x] Incluir na página de robô a versão do Automate utilizada (evitando erros de versão durante sua utilização).

## Fluxos internos DCD
- [x] Reunião de alinhamento da equipe toda segunda às 14.
- [x] Próxima segunda discutir pontos com os listados [neste Issue](https://github.com/lab-mg/novas-ideias/issues/20).
- [x] automatiza-mg/automatizacoes#65

**Comment by Andrelamor** [comment]
tendo em vista o lançamento do projeto, do site e do curso EaD, creio que este issue foi quase completo, a não ser pela reestruturação da rede de simplificação, objeto também do https://github.com/automatiza-mg/automatizacoes/issues/68

**Comment by gabrielbdornas** [comment]
> tendo em vista o lançamento do projeto, do site e do curso EaD, creio que este issue foi quase completo, a não ser pela reestruturação da rede de simplificação, objeto também do [automatiza-mg/automatizacoes#68](https://github.com/automatiza-mg/automatizacoes/issues/68)

@Andrelamor, perfeito. Vou fechar o Issue. Valeu pelo apoio.
